version: 2
jobs:
    check:
        docker:
            - image: circleci/android:api-27-alpha
        steps:
            - checkout
            - run:
                name: Clean
                command: ./gradlew clean
            - run:
                name: Run lint
                command: ./gradlew lintRelease
            - store_artifacts:
                path: app/build/reports/lint-results-release.html
            - run:
                name: Run detekt
                command: ./gradlew detektCheck
            - store_artifacts:
                path: app/build/reports/detekt-report.html
            - run:
                name: Run ktlint check
                command: ./gradlew ktlintCheck
            - run:
                name: Run ktlint format
                command: ./gradlew ktlintFormat

    test:
        docker:
            - image: circleci/android:api-27-alpha
        steps:
            - checkout
            - run:
                name: Clean
                command: ./gradlew clean
            - run:
                name: Run unit tests with report
                command: ./gradlew jacocoTestReport
            - store_artifacts:
                path: app/build/reports/tests
            - store_artifacts:
                path: app/build/reports/jacocoTestReport/html

    build:
        docker:
            - image: circleci/android:api-27-alpha
        steps:
            - checkout
            - run:
                name: Clean
                command: ./gradlew clean
            - run:
                name: Download keystore
                command: curl -L -o ./app/release.jks $KEYSTORE_PATH
            - run:
                name: Build apk
                command: ./gradlew assembleRelease
            - store_artifacts:
                path: app/build/outputs/apk/release/app-release.apk


workflows:
    version: 2
    check_test_build:
        jobs:
            - check
            - test
            - build:
                requires:
                    - check
                    - test
                filters:
                    branches:
                        only: master

