version: 2
jobs:
    check:
        docker:
            - image: circleci/android
        steps:
            - checkout
            - run:
                name: Clean
                command: ./gradlew clean
            - run:
                name: Run lint
                command: ./gradlew lintRelease
            - store_artifacts:
                path: app/build/reports/lint-results-release.html

    test:
        docker:
            - image: circleci/android
        steps:
            - checkout
            - run:
                name: Clean
                command: ./gradlew clean
            - run:
                name: Run tests
                command: ./gradlew testRelease
            - store_test_results:
                path: app/build/reports/tests

    build:
        docker:
            - image: circleci/android
        steps:
            - checkout
            - run:
                name: Clean
                command: ./gradlew clean
            - run:
                name: Download keystore
                command: curl -L -o ./app/release.jks $KEYSTORE_PATH
            - run:
                name: Build apk
                command: ./gradlew assembleRelease
            - store_artifacts:
                path: app/build/outputs/apk/release/app-release.apk


workflows:
    version: 2
    check_test_build:
        jobs:
            - check
            - test
            - build:
                requires:
                    - check
                    - test
                filters:
                    branches:
                        only: master

